# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
force true

price_tier 0
automatic_release true
overwrite_screenshots true
reject_if_possible true
run_precheck_before_submit false
screenshots_path "./docs"
submit_for_review true

submission_information({
  add_id_info_serves_ads: false,
  add_id_info_tracks_action: false,
  add_id_info_tracks_install: false,
  add_id_info_uses_idfa: false,
  content_rights_has_rights: false,
  content_rights_contains_third_party_content: false,

  export_compliance_app_type: nil,
  export_compliance_is_exempt: true,

  export_compliance_platform: 'ios',
  export_compliance_compliance_required: false,
  export_compliance_encryption_updated: false,
  export_compliance_uses_encryption: false,
  export_compliance_contains_third_party_cryptography: false,
  export_compliance_contains_proprietary_cryptography: false,
  export_compliance_available_on_french_store: false
})
