# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Send HueBoo to TestFlight."
  lane :release_to_testflight do
    build_for_apple_distribution(configuration: "Beta")
    pilot(
      ipa: "./fastlane/apple_build/Missions.ipa",
      skip_waiting_for_build_processing: false,
      changelog: "Version {lane_context[SharedValues: VERSION_NUMBER]}, Build {lane_context[SharedValues: BUILD_NUMBER]}",
      uses_non_exempt_encryption: false
    )
  end
  
  desc "Build for either TestFlight or AppStore"
  lane :build_for_apple_distribution do |configuration|
    precheck
    unit_test
    ui_test
    create_screenshots
    match_with_options(type: "appstore")
    increment_build_number(build_number: Time.now.to_i)
    gym(
      configuration: configuration[:configuration],
      export_method: "app-store",
      output_directory: "./fastlane/apple_build"
    )
  end

  desc "Resolve Signing Certificates and Provisioning Profiles."
  lane :match_with_options do |options|
    matchType = options[:type]
    match(type: matchType, readonly: true)
  end

  desc "Create and Frame Screenshots of Missions."
  lane :create_screenshots do
    snapshot
    frameit(path: "./docs", rose_gold: true)
  end

  desc "Unit Test Missions."
  lane :unit_test do
    scan(only_testing: "MissionsTests", configuration: "Debug")
  end

  desc "UI Test Missions."
  lane :ui_test do
    scan(only_testing: "MissionsUITests", configuration: "Debug")
  end
end
