# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Send Missions to AppStore."
  lane :release_to_appstore do
    build_for_apple_distribution(configuration: "AppStore")
    # create_screenshots
    deliver
  end

  desc "Send Missions to TestFlight."
  lane :release_to_external_testers do
    # Image Generated at https://onlinetexttools.com/convert-text-to-image: 1024 x 1024 PNG
    # add_badge(custom: "fastlane/beta-overlay.png")
    build_for_apple_distribution(configuration: "Beta")
    pilot(
      ipa: "./fastlane/apple_build/Missions.ipa",
      skip_waiting_for_build_processing: false,
      changelog: "Version {lane_context[SharedValues: VERSION_NUMBER]}, Build {lane_context[SharedValues: BUILD_NUMBER]}",
      uses_non_exempt_encryption: false,
      distribute_external: true,
      groups: "Nightly",
      beta_app_review_info: {
        contact_email: ENV['CONTACT_EMAIL'],
        contact_first_name: ENV['CONTACT_FIRST_NAME'],
        contact_last_name: ENV['CONTACT_LAST_NAME'],
        contact_phone: ENV['CONTACT_PHONE'],
        # demo_account_name: "demo@email.com",
        # demo_account_password: "connectapi",
        notes: "this is review note for the reviewer <3 thank you for reviewing"
      },
      localized_app_info: {
        "default": {
          feedback_email: ENV['FEEDBACK_EMAIL'],
          marketing_url: ENV['MARKETING_URL'],
          privacy_policy_url: ENV['PRIVACY_POLICY_URL'],
          description: "Default description",
        }
      },
      localized_build_info: {
        "default": {
          whats_new: "Default changelog",
        }
      }
    )
  end

  desc "Send Missions to TestFlight."
  lane :release_to_internal_testers do
    add_badge(custom: "beta-overlay.png")
    build_for_apple_distribution(configuration: "Debug")
    pilot(
      ipa: "./fastlane/apple_build/Missions.ipa",
      skip_waiting_for_build_processing: false,
      changelog: "Version {lane_context[SharedValues: VERSION_NUMBER]}, Build {lane_context[SharedValues: BUILD_NUMBER]}",
      uses_non_exempt_encryption: false,
      groups: "Developers",
      beta_app_review_info: {
        contact_email: ENV['CONTACT_EMAIL'],
        contact_first_name: ENV['CONTACT_FIRST_NAME'],
        contact_last_name: ENV['CONTACT_LAST_NAME'],
        contact_phone: ENV['CONTACT_PHONE'],
        # demo_account_name: "demo@email.com",
        # demo_account_password: "connectapi",
        notes: "this is review note for the reviewer <3 thank you for reviewing"
      },
      localized_app_info: {
        "default": {
          feedback_email: ENV['FEEDBACK_EMAIL'],
          marketing_url: ENV['MARKETING_URL'],
          privacy_policy_url: ENV['PRIVACY_POLICY_URL'],
          description: "Default description",
        }
      },
      localized_build_info: {
        "default": {
          whats_new: "Default changelog",
        }
      }
    )
  end

  desc "Build for either TestFlight or AppStore"
  lane :build_for_apple_distribution do |configuration|
    setup_ci
    setup_app_store_connect_api_key
    sh("bash GooglePlistGenerationScript.sh")
    # create_screenshots
    match(readonly: true)
    increment_build_number(build_number: Time.now.to_i)
    gym(
      configuration: configuration[:configuration],
      export_method: "app-store",
      output_directory: "./fastlane/apple_build"
    )
  end

  desc "Update AppStore Privacy Details"
  lane :update_privacy_details do
    upload_app_privacy_details_to_app_store(
      username: ENV['APPLE_ID'],
      team_name: ENV['APP_STORE_CONNECT_KEY_ID'],
      app_identifier: ENV['APP_IDENTIFIER'],
      json_path: "fastlane/app_privacy_details.json"
    )
  end

  desc "Setup AppStore Connect API Key."
  lane :setup_app_store_connect_api_key do
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_KEY_CONTENT']
    )
  end

  # desc "Resolve Signing Certificates and Provisioning Profiles."
  # # See https://docs.github.com/en/rest/overview/other-authentication-methods#basic-authentication
  # # for info on setting the MATCH_GIT_BASIC_AUTHORIZATION environment variable
  # lane :match_with_options do |options|
  #   matchType = options[:type]
  #   match(type: matchType, readonly: true)
  # end

  desc "Create and Frame Screenshots of Missions."
  lane :create_screenshots do
    snapshot
    frameit(path: "./docs", rose_gold: true)
  end

  desc "Unit Test Missions."
  lane :unit_test do
    scan(only_testing: "MissionsTests", configuration: "Debug")
  end

  desc "UI Test Missions."
  lane :ui_test do
    scan(only_testing: "MissionsUITests", configuration: "Debug")
  end
end
