name: Release To AppStore
on:
  push:
    branches:
    - main
jobs:
  release:
    name: Use Bundler & Fastlane to Deploy to Appstore
    runs-on: macOS-latest
    environment: Production
    env:
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
      MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Bundler
        run: bundle install
      - name: Release To AppStore
        run: bundle exec fastlane release_to_appstore
