name: CI
on:
  push:
    branches:
    - develop
jobs:
  beta:
    name: Release to Developers
    runs-on: macOS-latest
    environment: Beta
    # strategy:
    #   matrix:
    #     destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8']
        # xcode: ['/Applications/Xcode_11.1.app/Contents/Developer']
    env:
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
      MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      CONTACT_FIRST_NAME: ${{ secrets.CONTACT_FIRST_NAME }}
      CONTACT_LAST_NAME: ${{ secrets.CONTACT_LAST_NAME }}
      CONTACT_PHONE: ${{ secrets.CONTACT_PHONE }}
      FEEDBACK_EMAIL: ${{ secrets.FEEDBACK_EMAIL }}
      MARKETING_URL: ${{ secrets.MARKETING_URL }}
      PRIVACY_POLICY_URL: ${{ secrets.PRIVACY_POLICY_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install
      # - name: Install Imagemagick
      #   run: brew install imagemagick
      # - name: Install librsvg
      #   run: brew install librsvg
      # - name: Install "Badge" Plugin
      #   run: bundle exec fastlane add_plugin badge
      - name: Release To Internal Testers
        run: bundle exec fastlane release_to_external_testers
